# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1014, 760)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.viewerWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.viewerWidget.setObjectName("viewerWidget")
        self.verticalLayout_2.addWidget(self.viewerWidget)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setObjectName("toolBox")
        self.ViewerPage = QtWidgets.QWidget()
        self.ViewerPage.setGeometry(QtCore.QRect(0, 0, 367, 624))
        self.ViewerPage.setObjectName("ViewerPage")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.ViewerPage)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_17 = QtWidgets.QLabel(self.ViewerPage)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_16.addWidget(self.label_17)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_6 = QtWidgets.QLabel(self.ViewerPage)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_12.addWidget(self.label_6)
        self.lightRed = QtWidgets.QDoubleSpinBox(self.ViewerPage)
        self.lightRed.setMaximum(255.0)
        self.lightRed.setSingleStep(0.1)
        self.lightRed.setProperty("value", 255.0)
        self.lightRed.setObjectName("lightRed")
        self.verticalLayout_12.addWidget(self.lightRed)
        self.verticalLayout_12.setStretch(1, 1)
        self.horizontalLayout_10.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.ViewerPage)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_13.addWidget(self.label_14)
        self.lightGreen = QtWidgets.QDoubleSpinBox(self.ViewerPage)
        self.lightGreen.setMaximum(255.0)
        self.lightGreen.setSingleStep(0.1)
        self.lightGreen.setProperty("value", 255.0)
        self.lightGreen.setObjectName("lightGreen")
        self.verticalLayout_13.addWidget(self.lightGreen)
        self.horizontalLayout_10.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_15 = QtWidgets.QLabel(self.ViewerPage)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_14.addWidget(self.label_15)
        self.lightBlue = QtWidgets.QDoubleSpinBox(self.ViewerPage)
        self.lightBlue.setMaximum(255.0)
        self.lightBlue.setSingleStep(0.1)
        self.lightBlue.setProperty("value", 255.0)
        self.lightBlue.setObjectName("lightBlue")
        self.verticalLayout_14.addWidget(self.lightBlue)
        self.horizontalLayout_10.addLayout(self.verticalLayout_14)
        self.verticalLayout_16.addLayout(self.horizontalLayout_10)
        self.verticalLayout_18.addLayout(self.verticalLayout_16)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_18 = QtWidgets.QLabel(self.ViewerPage)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_23.addWidget(self.label_18)
        self.rotAngle = QtWidgets.QDoubleSpinBox(self.ViewerPage)
        self.rotAngle.setMinimum(1.0)
        self.rotAngle.setMaximum(360.0)
        self.rotAngle.setSingleStep(0.1)
        self.rotAngle.setProperty("value", 45.0)
        self.rotAngle.setObjectName("rotAngle")
        self.verticalLayout_23.addWidget(self.rotAngle)
        self.horizontalLayout_11.addLayout(self.verticalLayout_23)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.ViewerPage)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.shinSpin = QtWidgets.QDoubleSpinBox(self.ViewerPage)
        self.shinSpin.setMinimum(1.0)
        self.shinSpin.setMaximum(300.0)
        self.shinSpin.setSingleStep(0.1)
        self.shinSpin.setObjectName("shinSpin")
        self.verticalLayout.addWidget(self.shinSpin)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout_11.addLayout(self.verticalLayout)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_16 = QtWidgets.QLabel(self.ViewerPage)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_17.addWidget(self.label_16)
        self.ambientCoeff = QtWidgets.QDoubleSpinBox(self.ViewerPage)
        self.ambientCoeff.setDecimals(2)
        self.ambientCoeff.setMaximum(1.0)
        self.ambientCoeff.setSingleStep(0.01)
        self.ambientCoeff.setProperty("value", 0.2)
        self.ambientCoeff.setObjectName("ambientCoeff")
        self.verticalLayout_17.addWidget(self.ambientCoeff)
        self.horizontalLayout_11.addLayout(self.verticalLayout_17)
        self.verticalLayout_18.addLayout(self.horizontalLayout_11)
        self.verticalLayout_15.addLayout(self.verticalLayout_18)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.ViewerPage)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.ViewerPage)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.rotCamX = QtWidgets.QSlider(self.ViewerPage)
        self.rotCamX.setOrientation(QtCore.Qt.Horizontal)
        self.rotCamX.setObjectName("rotCamX")
        self.horizontalLayout_7.addWidget(self.rotCamX)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.ViewerPage)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.rotCamY = QtWidgets.QSlider(self.ViewerPage)
        self.rotCamY.setOrientation(QtCore.Qt.Horizontal)
        self.rotCamY.setObjectName("rotCamY")
        self.horizontalLayout_8.addWidget(self.rotCamY)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_13 = QtWidgets.QLabel(self.ViewerPage)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_9.addWidget(self.label_13)
        self.rotCamZ = QtWidgets.QSlider(self.ViewerPage)
        self.rotCamZ.setOrientation(QtCore.Qt.Horizontal)
        self.rotCamZ.setObjectName("rotCamZ")
        self.horizontalLayout_9.addWidget(self.rotCamZ)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.ViewerPage)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.camMoveUp = QtWidgets.QPushButton(self.ViewerPage)
        self.camMoveUp.setAutoRepeat(True)
        self.camMoveUp.setObjectName("camMoveUp")
        self.verticalLayout_6.addWidget(self.camMoveUp)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.camMoveLeft = QtWidgets.QPushButton(self.ViewerPage)
        self.camMoveLeft.setAutoRepeat(True)
        self.camMoveLeft.setObjectName("camMoveLeft")
        self.horizontalLayout_3.addWidget(self.camMoveLeft)
        self.camMoveDown = QtWidgets.QPushButton(self.ViewerPage)
        self.camMoveDown.setAutoRepeat(True)
        self.camMoveDown.setObjectName("camMoveDown")
        self.horizontalLayout_3.addWidget(self.camMoveDown)
        self.camMoveRight = QtWidgets.QPushButton(self.ViewerPage)
        self.camMoveRight.setAutoRepeat(True)
        self.camMoveRight.setObjectName("camMoveRight")
        self.horizontalLayout_3.addWidget(self.camMoveRight)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_10.addLayout(self.verticalLayout_7)
        self.verticalLayout_15.addLayout(self.verticalLayout_10)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.ViewerPage)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.ViewerPage)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.rotLightX = QtWidgets.QSlider(self.ViewerPage)
        self.rotLightX.setOrientation(QtCore.Qt.Horizontal)
        self.rotLightX.setObjectName("rotLightX")
        self.horizontalLayout_6.addWidget(self.rotLightX)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.ViewerPage)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.rotLightY = QtWidgets.QSlider(self.ViewerPage)
        self.rotLightY.setOrientation(QtCore.Qt.Horizontal)
        self.rotLightY.setObjectName("rotLightY")
        self.horizontalLayout_5.addWidget(self.rotLightY)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.ViewerPage)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.rotLightZ = QtWidgets.QSlider(self.ViewerPage)
        self.rotLightZ.setOrientation(QtCore.Qt.Horizontal)
        self.rotLightZ.setObjectName("rotLightZ")
        self.horizontalLayout_4.addWidget(self.rotLightZ)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.verticalLayout_11.addLayout(self.verticalLayout_8)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.ViewerPage)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lightMoveUp = QtWidgets.QPushButton(self.ViewerPage)
        self.lightMoveUp.setAutoRepeat(True)
        self.lightMoveUp.setObjectName("lightMoveUp")
        self.verticalLayout_3.addWidget(self.lightMoveUp)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lightMoveLeft = QtWidgets.QPushButton(self.ViewerPage)
        self.lightMoveLeft.setAutoRepeat(True)
        self.lightMoveLeft.setObjectName("lightMoveLeft")
        self.horizontalLayout.addWidget(self.lightMoveLeft)
        self.lightMoveDown = QtWidgets.QPushButton(self.ViewerPage)
        self.lightMoveDown.setAutoRepeat(True)
        self.lightMoveDown.setObjectName("lightMoveDown")
        self.horizontalLayout.addWidget(self.lightMoveDown)
        self.lightMoveRight = QtWidgets.QPushButton(self.ViewerPage)
        self.lightMoveRight.setAutoRepeat(True)
        self.lightMoveRight.setObjectName("lightMoveRight")
        self.horizontalLayout.addWidget(self.lightMoveRight)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_15.addLayout(self.verticalLayout_4)
        self.verticalLayout_15.setStretch(1, 1)
        self.verticalLayout_15.setStretch(2, 1)
        self.verticalLayout_20.addLayout(self.verticalLayout_15)
        self.toolBox.addItem(self.ViewerPage, "")
        self.ImageListPage = QtWidgets.QWidget()
        self.ImageListPage.setGeometry(QtCore.QRect(0, 0, 278, 624))
        self.ImageListPage.setObjectName("ImageListPage")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.ImageListPage)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.fileList = QtWidgets.QListWidget(self.ImageListPage)
        self.fileList.setObjectName("fileList")
        self.verticalLayout_21.addWidget(self.fileList)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.loadFile = QtWidgets.QPushButton(self.ImageListPage)
        self.loadFile.setObjectName("loadFile")
        self.verticalLayout_19.addWidget(self.loadFile)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.addFile = QtWidgets.QPushButton(self.ImageListPage)
        self.addFile.setObjectName("addFile")
        self.horizontalLayout_13.addWidget(self.addFile)
        self.removeFile = QtWidgets.QPushButton(self.ImageListPage)
        self.removeFile.setObjectName("removeFile")
        self.horizontalLayout_13.addWidget(self.removeFile)
        self.verticalLayout_19.addLayout(self.horizontalLayout_13)
        self.verticalLayout_21.addLayout(self.verticalLayout_19)
        self.toolBox.addItem(self.ImageListPage, "")
        self.horizontalLayout_2.addWidget(self.toolBox)
        self.horizontalLayout_2.setStretch(0, 1)
        self.verticalLayout_22.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1014, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Viewer"))
        self.label_17.setText(_translate("MainWindow", "Light Color"))
        self.label_6.setText(_translate("MainWindow", "red"))
        self.label_14.setText(_translate("MainWindow", "green"))
        self.label_15.setText(_translate("MainWindow", "blue"))
        self.label_18.setText(_translate("MainWindow", "Angle"))
        self.label.setText(_translate("MainWindow", "Shininess"))
        self.label_16.setText(_translate("MainWindow", "Ambient Coefficient"))
        self.label_10.setText(_translate("MainWindow", "Rotate Camera"))
        self.label_11.setText(_translate("MainWindow", "x"))
        self.label_12.setText(_translate("MainWindow", "y"))
        self.label_13.setText(_translate("MainWindow", "z"))
        self.label_4.setText(_translate("MainWindow", "Move Camera"))
        self.camMoveUp.setText(_translate("MainWindow", "^"))
        self.camMoveLeft.setText(_translate("MainWindow", "<"))
        self.camMoveDown.setText(_translate("MainWindow", "v"))
        self.camMoveRight.setText(_translate("MainWindow", ">"))
        self.label_5.setText(_translate("MainWindow", "Rotate Light"))
        self.label_8.setText(_translate("MainWindow", "x"))
        self.label_9.setText(_translate("MainWindow", "y"))
        self.label_7.setText(_translate("MainWindow", "z"))
        self.label_3.setText(_translate("MainWindow", "Move Light"))
        self.lightMoveUp.setText(_translate("MainWindow", "^"))
        self.lightMoveLeft.setText(_translate("MainWindow", "<"))
        self.lightMoveDown.setText(_translate("MainWindow", "v"))
        self.lightMoveRight.setText(_translate("MainWindow", ">"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ViewerPage), _translate("MainWindow", "Viewer"))
        self.loadFile.setText(_translate("MainWindow", "Load"))
        self.addFile.setText(_translate("MainWindow", "Add File(s)"))
        self.removeFile.setText(_translate("MainWindow", "Remove File(s)"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ImageListPage), _translate("MainWindow", "File List"))

