# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1071, 779)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.MainLayout = QtWidgets.QVBoxLayout()
        self.MainLayout.setObjectName("MainLayout")
        self.ButtonsLayout = QtWidgets.QHBoxLayout()
        self.ButtonsLayout.setObjectName("ButtonsLayout")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setObjectName("listWidget")
        self.ButtonsLayout.addWidget(self.listWidget)
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setObjectName("openGLWidget")
        self.ButtonsLayout.addWidget(self.openGLWidget)
        self.ButtonsLayout.setStretch(1, 1)
        self.MainLayout.addLayout(self.ButtonsLayout)
        self.ControllersLayout = QtWidgets.QHBoxLayout()
        self.ControllersLayout.setObjectName("ControllersLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.importBtn = QtWidgets.QPushButton(self.centralwidget)
        self.importBtn.setObjectName("importBtn")
        self.verticalLayout_2.addWidget(self.importBtn)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.loadBtn = QtWidgets.QPushButton(self.centralwidget)
        self.loadBtn.setObjectName("loadBtn")
        self.horizontalLayout_4.addWidget(self.loadBtn)
        self.renderBtn = QtWidgets.QPushButton(self.centralwidget)
        self.renderBtn.setObjectName("renderBtn")
        self.horizontalLayout_4.addWidget(self.renderBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saveBtn = QtWidgets.QPushButton(self.centralwidget)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout_3.addWidget(self.saveBtn)
        self.quitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.quitBtn.setObjectName("quitBtn")
        self.horizontalLayout_3.addWidget(self.quitBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.ControllersLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ambientTermLabel = QtWidgets.QLabel(self.centralwidget)
        self.ambientTermLabel.setObjectName("ambientTermLabel")
        self.verticalLayout_4.addWidget(self.ambientTermLabel)
        self.ambientTermSpin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ambientTermSpin.setObjectName("ambientTermSpin")
        self.verticalLayout_4.addWidget(self.ambientTermSpin)
        self.diffuseCoeffLabel = QtWidgets.QLabel(self.centralwidget)
        self.diffuseCoeffLabel.setObjectName("diffuseCoeffLabel")
        self.verticalLayout_4.addWidget(self.diffuseCoeffLabel)
        self.diffuseCoeffSpin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.diffuseCoeffSpin.setObjectName("diffuseCoeffSpin")
        self.verticalLayout_4.addWidget(self.diffuseCoeffSpin)
        self.ControllersLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.zoomLabel = QtWidgets.QLabel(self.centralwidget)
        self.zoomLabel.setObjectName("zoomLabel")
        self.verticalLayout_3.addWidget(self.zoomLabel)
        self.zoomSlider = QtWidgets.QSlider(self.centralwidget)
        self.zoomSlider.setOrientation(QtCore.Qt.Horizontal)
        self.zoomSlider.setObjectName("zoomSlider")
        self.verticalLayout_3.addWidget(self.zoomSlider)
        self.lightIntensityLabel = QtWidgets.QLabel(self.centralwidget)
        self.lightIntensityLabel.setObjectName("lightIntensityLabel")
        self.verticalLayout_3.addWidget(self.lightIntensityLabel)
        self.lightIntensitySlider = QtWidgets.QSlider(self.centralwidget)
        self.lightIntensitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.lightIntensitySlider.setObjectName("lightIntensitySlider")
        self.verticalLayout_3.addWidget(self.lightIntensitySlider)
        self.ControllersLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lightDirectionLabel = QtWidgets.QLabel(self.centralwidget)
        self.lightDirectionLabel.setObjectName("lightDirectionLabel")
        self.verticalLayout_5.addWidget(self.lightDirectionLabel)
        self.lightDirDial = QtWidgets.QDial(self.centralwidget)
        self.lightDirDial.setObjectName("lightDirDial")
        self.verticalLayout_5.addWidget(self.lightDirDial)
        self.ControllersLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.specColorLabel = QtWidgets.QLabel(self.centralwidget)
        self.specColorLabel.setObjectName("specColorLabel")
        self.verticalLayout.addWidget(self.specColorLabel)
        self.specColorSpin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.specColorSpin.setObjectName("specColorSpin")
        self.verticalLayout.addWidget(self.specColorSpin)
        self.shinenessLabel = QtWidgets.QLabel(self.centralwidget)
        self.shinenessLabel.setObjectName("shinenessLabel")
        self.verticalLayout.addWidget(self.shinenessLabel)
        self.shininessSpin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.shininessSpin.setObjectName("shininessSpin")
        self.verticalLayout.addWidget(self.shininessSpin)
        self.ControllersLayout.addLayout(self.verticalLayout)
        self.MainLayout.addLayout(self.ControllersLayout)
        self.verticalLayout_6.addLayout(self.MainLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1071, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.importBtn.setText(_translate("MainWindow", "Import Files"))
        self.loadBtn.setText(_translate("MainWindow", "Load"))
        self.renderBtn.setText(_translate("MainWindow", "Render"))
        self.saveBtn.setText(_translate("MainWindow", "Save"))
        self.quitBtn.setText(_translate("MainWindow", "Quit"))
        self.ambientTermLabel.setText(_translate("MainWindow", "Ambient Term"))
        self.diffuseCoeffLabel.setText(_translate("MainWindow", "Diffuse Coefficient"))
        self.zoomLabel.setText(_translate("MainWindow", "Zoom"))
        self.lightIntensityLabel.setText(_translate("MainWindow", "Light Intensity"))
        self.lightDirectionLabel.setText(_translate("MainWindow", "Light Direction"))
        self.specColorLabel.setText(_translate("MainWindow", "Specular Color"))
        self.shinenessLabel.setText(_translate("MainWindow", "Shininess"))

